<a href="https://colab.research.google.com/github/ahmedSadoun/while-studing-training-/blob/main/practice_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:

name=input('plz enter ur name : ')
age=input('plz enter ur age : ')
hudred=100-int(age)
print('hi '+name+'you will turn 100 after '+str(hudred))


plz enter ur name : ahmed
plz enter ur age : 23
hi ahmedyou will turn 100 after 77


the link of the blog i follow : 
https://www.analyticsvidhya.com/blog/2020/04/the-ultimate-numpy-tutorial-for-data-science-beginners/

In [ ]:
import numpy as np
print(np.__version__)
print(np.show_config())

1.19.5
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
None


In [ ]:
print(np.info(np.add))

None


In [ ]:
#check if the array contains zero or not 
array=np.arange(0,6)
print(array.size)
print(np.all(array))
x=True
for s in range(array.size):
  if array[s] / 1 == 0 :
    x=False
if x ==False : 
  print('the array contains zero')


6
False
the array contains zero


In [ ]:
#check wether a number of an array in non zero 
zeroArray=[0,0,1,0,0]
print(zeroArray)
nonZeroItems=np.count_nonzero(zeroArray)
if nonZeroItems == 0 :
  print('non zero items found')
else:
  print('zero items found ')

[0, 0, 1, 0, 0]
zero items found 


In [ ]:
a=np.array([1,2,np.nan,np.nan])
print(a)
print(np.isfinite(a))

[ 1.  2. nan nan]
[ True  True False False]


In [ ]:
#check if the array has a nan values 
a=np.array([1,0,np.nan,np.nan])
print(np.isnan(a))

[False False  True  True]


In [ ]:
arr=np.array([1+1j,1+0j,4.5,3,2j])
print(np.isreal(arr))

[False  True  True  True False]


In [ ]:
one=np.arange(6)
two=np.arange(6)
np.equal(one,two)

array([ True,  True,  True,  True,  True,  True])

In [ ]:
'''Write a NumPy program to create an element-wise comparison 
(greater, greater_equal, less and less_equal) of two given arrays.
'''
x = np.array([3, 5])
y = np.array([2, 5])
print(np.greater(x,y))
print(np.greater_equal(x,y))
print(np.less(x,y))
print(np.less_equal(x,y))

[ True False]
[ True  True]
[False False]
[False  True]


In [ ]:
import numpy as np


In [ ]:
#it creates a random n dimension ndarray from 0 to 1
np.random.rand(2,3,3)

array([[[0.8354067 , 0.096269  , 0.45685004],
        [0.32922109, 0.53063688, 0.749603  ],
        [0.02915137, 0.86320336, 0.81637914]],

       [[0.79219777, 0.49559885, 0.16884452],
        [0.14635863, 0.40031024, 0.37840208],
        [0.4702705 , 0.79926585, 0.70294065]]])

In [ ]:
'''Or, in fact, you can create an array filled with any given value using the np.full() method. 
Just pass in the shape of the desired array and the value you want:'''
np.full((2,2),5)

array([[5, 5],
       [5, 5]])

In [ ]:
''' 
Another great method is np.eye() that returns an array with 1s along its diagonal and 0s everywhere else.
'''
#identity matrix 
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
''' 
However, NumPy gives you the flexibility to change the diagonal along which the values have to be 1s. You can either move it above the main diagonal:
''' 
np.eye(3,k=2)

array([[0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
# 5 is the start number , 8 is the stop number , 1 is the step
np.arange(5,8,1)

array([5, 6, 7])

In [ ]:
''' 
Another similar function is np.linspace(), but instead of step size, it takes in the number of samples that need to be retrieved from the interval. 
A point to note here is that the last number is included in the values returned unlike in the case of np.arange().
'''
# 0 start number , 1 stop , 5 is how many numbers i need between the two interval 
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
#You can easily determine the number of dimensions or axes of a NumPy array using the ndims attribute:
a=np.array([np.arange(5),np.arange(5)])
np.ndim(a)
print('the shape ', a.shape)
print('rows', a.shape[0])
print('columns', a.shape[1])
#it returns the number of the values in the np array
print('the size', a.size)
print('this how to calculate the np array size manually : ',a.shape[0]*a.shape[1])

the shape  (2, 5)
rows 2
columns 5
the size 10
this how to calculate the np array size manually :  10


In [ ]:
'''
Reshaping a ndarray can be done using the np.reshape() method. It changes the shape of the ndarray without changing the data within the ndarray:
'''
s=np.array([1,2,3,4])
s.reshape((2,2))
#or 
np.reshape(s,(2,2))

array([[1, 2],
       [3, 4]])

In [ ]:
'''
While reshaping, if you are unsure about the shape of any of the axis, just input -1. NumPy automatically calculates the shape when it sees a -1:
'''
np.reshape(s,(2,-1))

array([[1, 2],
       [3, 4]])

In [ ]:
'''Sometimes when you have a multidimensional array and want to collapse it to a single-dimensional array, 
you can either use the flatten() method or the ravel() method:'''

a=np.ones((2,2))
a
a.flatten()
'''But an important difference between flatten() and ravel() is that the former returns a copy of the original array while the latter returns a reference to the original array. 
This means any changes made to the array returned from ravel() will also be reflected in the original array while this will not be the case with flatten().
What is happening here is that flatten() creates a Deep copy of the ndarray while ravel() creates a Shallow copy of the ndarray.

Deep copy means that a completely new ndarray is created in memory and the ndarray object returned by flatten() is now pointing to this memory location.
Therefore, any changes made here will not be reflected in the original ndarray.

A Shallow copy, on the other hand, returns a reference to the original memory location. Meaning the object returned by ravel() is pointing to the same memory location as the original ndarray object. 
So, definitely, any changes made to this ndarray will also be reflected in the original ndarray too.
'''

array([[1., 1.],
       [1., 1.]])

Another very interesting reshaping method of NumPy is the transpose() method. It takes the input array and swaps the rows with the column values, and the column values with the values of the rows:**bold text**

In [ ]:
matrix=np.array([[np.arange(3)],[np.arange(3,6)]])
print(matrix)
t_matrix=np.transpose(matrix)
print('_______________________')
print(t_matrix)

[[[0 1 2]]

 [[3 4 5]]]
_______________________
[[[0 3]]

 [[1 4]]

 [[2 5]]]


Expanding a NumPy array
You can add a new axis to an array using the expand_dims() method by providing the array and the axis along which to expand:

In [ ]:
a=np.array([1,2,3])
print(a)
#axis = 0 means expand along column dimension 
#axis =1 means expand along rows dimension
'''
فكرة زيادة محور .. عندي الاراي بتكون مجموعة ارقام ملهاش محور معين 
ف الما اعمل اكسباند دايمنشن ف انا ب امسك الارقام دي احطها علي محور معين 
صفر علشان احطها ع المحور الافقي يعني اعمدة 
واحد يعني احطهم علي المحور العمودي يعني صفوف
'''
s=np.expand_dims(a,axis=0)
print(s)

[1 2 3]
[[1 2 3]]


**Squeezing a NumPy array:**
On the other hand, if you instead want to reduce the axis of the array, use the squeeze() method. It removes the axis that has a single entry. This means if you have created a 2 x 2 x 1 matrix, squeeze() will remove the third dimension from the matrix:

In [ ]:
'''
squeeze 
دا بيقلل ال دايمنشن .. يعني بيكون عندي مجموعة قيم ماتريكس 
محطوتين ف 3 ابعاد و لكن البعد التالت مش موجود ليه قيم 
ف انا ب اعمل ضغط ب اشيل بيه البعد التالت 
او بيكون عندي صف قيم بس محطوتين ف بعدين ب اشيل بعد و اخلي واحد
'''
q=np.array([[[1,2,3],[4,5,6]]])
print(q)
print('______________________')
print(np.squeeze(q,axis=0))
n=np.array([[1,2,3]])
print('\n',n)
print('_____________________')
print(np.squeeze(n,axis=0))



[[[1 2 3]
  [4 5 6]]]
______________________
[[1 2 3]
 [4 5 6]]

 [[1 2 3]]
_____________________
[1 2 3]


# **Slicing 1-D NumPy arrays**
Slicing means retrieving elements from one index to another index. All we have to do is to pass the starting and ending point in the index like this: [start: end].

However, you can even take it up a notch by passing the step-size. What is that? Well, suppose you wanted to print every other element from the array, you would define your step-size as 2, meaning get the element 2 places away from the present index.

Incorporating all this into a single index would look something like this: [start:end:step-size].

In [ ]:
#           0 1 2 3 4 5 6 7 8
s=np.array([1,2,3,4,5,6,7,8,9])
#bring from index 1 to 3-1
#the default step is 1
slic=s[1:3]
#the step is 2
slic_2=s[1:6:2]
#the first index is 0 as default 
slic_3=s[:6]
print(slic,"\n\n",slic_2)


[2 3] 

 [2 4 6]


# **Slicing 2-D NumPy arrays**
Now, a 2-D array has rows and columns so it can get a little tricky to slice 2-D arrays. But once you understand it, you can slice any dimension array!

Before learning how to slice a 2-D array, let’s have a look at how to retrieve an element from a 2-D array:

In [ ]:
v=np.array([[1,2,3],[4,5,6]])
print(v,'\n')
#Here, we provided the row value and column value to identify the element we wanted to extract
print(v[0,0])
print(v[0,1])
print('##########################################\n')
#   rows      column
#v[from : to , from:to]
print(v[0:1,0:3])


[[1 2 3]]



## Slicing 3-D NumPy arrays
So far we haven’t seen a 3-D array. Let’s first visualize how a 3-D array looks like:

In [ ]:
ddd=np.array([[
               [1,2],[3,4],[5,6]],
          [[16,7],[8,9],[10,11]],
          [[12,13],[14,15],[16,17]]])
ddd

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[16,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]]])

In addition to the rows and columns, as in a 2-D array, a 3-D array also has a depth axis where it stacks one 2-D array behind the other. So, when you are slicing a 3-D array, you also need to mention which 2-D array you are slicing. This usually comes as the first value in the index:

In [ ]:
'''   define what       define the      define the 
      matrix we are     rows index      column index
      working on                                          '''
# ddd[from : to       , 0;1        ,   0:1 ]
''' احنا هنا بنحدد كام مصفوفه هنشتغل عليها و بعدين بنحدد الصفوف و بعدين الاعمدة '''
print(ddd[0:3,0:1,0:1])

[[[ 1]]

 [[16]]

 [[12]]]


In [ ]:
#create a 3d matrix 
mat=np.linspace(0,20,18)
np.reshape(mat,(3,2,3))
#or
mat_2=np.arange(0,18,1)
resh=np.reshape(mat_2,(3,2,3))
resh

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17]]])

# Negative slicing of NumPy arrays
An interesting way to slice your array is to use negative slicing. Negative slicing prints elements from the end rather than the beginning. Have a look below:

In [ ]:
neg_matrix=np.arange(0,16,1)
themat=np.reshape(neg_matrix,(4,4
                              ))
print(themat,'\n')

print(themat[0:2:,-3:-1])
#to reverse a matrix 
#               step
print(themat[::-1,::-1])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]] 

[[1 2]
 [5 6]]
[[15 14 13 12]
 [11 10  9  8]
 [ 7  6  5  4]
 [ 3  2  1  0]]


# Stacking and Concatenating NumPy arrays
# Stacking ndarrays
You can create a new array by combining existing arrays. This you can do in two ways:

Either combine the arrays vertically (i.e. along the rows) using the** vstack()** method, thereby increasing the number of rows in the resulting array.

Or combine the arrays in a horizontal fashion (i.e. along the columns) using the **hstack()**, thereby increasing the number of columns in the resultant array.

In [ ]:
firstarray=np.arange(0,5)
secondarray=np.arange(5,10)
# the two arrays must match in length 
vstack=np.vstack((firstarray,secondarray))
#the two arrays are not necessaty to match in length
hstack=np.hstack((firstarray,secondarray))
#it combines the two arrays along the third axis . the depth one
depthstack=np.dstack((firstarray,secondarray))
print(depthstack,'\n\n',hstack)

[[[0 5]
  [1 6]
  [2 7]
  [3 8]
  [4 9]]] 

 [0 1 2 3 4 5 6 7 8 9]


# Concatenating ndarrays
While stacking arrays is one way of combining old arrays to get a new one, you could also use the concatenate() method where the passed arrays are joined along an existing axis:

In [ ]:
x=np.arange(0,5).reshape(1,5)
y=np.arange(5,10).reshape(1,5)
#vertical = 0 incresing the number of rows 
#horizontal=1 increase the number of columns 
concat=np.concatenate((x,y),axis=1)
squeeze=np.squeeze(concat)
squeeze

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Another very useful function is the append method that adds new elements to the end of a ndarray. This is obviously useful when you already have an existing ndarray but want to add new values to it.

In [ ]:
arr=np.array([[2,3],[6,7]])
print(np.append(arr,[[15,16]],axis=0))

[[ 2  3]
 [ 6  7]
 [15 16]]


# Broadcasting in NumPy arrays – A class apart!
Broadcasting is one of the best features of ndarrays. It lets you perform arithmetics operations between ndarrays of different sizes or between an ndarray and a simple number!

Broadcasting essentially stretches the smaller ndarray so that it matches the shape of the larger ndarray:

In [ ]:
import numpy as np

In [ ]:
rasn=np.arange(1,5)
arr=np.array([[2],[3]])
print(rasn+arr)
print('\n\n',rasn*arr)

[[3 4 5 6]
 [4 5 6 7]]


 [[ 2  4  6  8]
 [ 3  6  9 12]]


You can also easily determine the index of the minimum or maximum value in the ndarray along a particular axis using the argmin() and argmax() methods:

In [ ]:
a=np.array([[0,1],[31,4]])
np.argmax(a,axis=1)
np.argmin(a,axis=0)

array([0, 0])

# Sorting in NumPy arrays
For any programmer, the time complexity of any algorithm is of prime essence. Sorting is an important and very basic operation that you might well use on a daily basis as a data scientist. So, it is important to use a good sorting algorithm with minimum time complexity.

The NumPy library is a legend when it comes to sorting elements of an array. It has a range of sorting functions that you can use to sort your array elements. It has implemented quicksort, heapsort, mergesort, and timesort for you under the hood when you use the sort() method:

In [ ]:
arr=np.array([14,5,4,6,0,7,20,15,88,94,11,1,12])
np.sort(arr,kind='quicksort')

array([ 0,  1,  4,  5,  6,  7, 11, 12, 14, 15, 20, 88, 94])

In [ ]:
mat=np.array([[1,2,4,8],[7,8,2,1]])
#vertical sort
np.sort(mat,kind='mergsort',axis=0)
#horizontal
np.sort(mat,kind='mergsort',axis=1)

array([[1, 2, 4, 8],
       [1, 2, 7, 8]])

# NumPy arrays and Images
NumPy arrays find wide use in storing and manipulating image data. But what is image data really?

Images are made up of pixels that are stored in the form of an array. Each pixel has a value ranging between 0 to 255 – 0 indicating a black pixel and 255 indicating a white pixel. A colored image consists of three 2-D arrays, one for each of the color channels: Red, Green, and Blue, placed back-to-back thus making a 3-D array. Each value in the array constitutes a pixel value. So, the size of the array depends on the number of pixels along each dimension.


In [ ]:
from scipy import misc
import cv2 as cv
import matplotlib.pyplot as plt

# read image
im = cv.imread('/content/Colourful Houses.jpg')
#we normalize the image for faster computaions
normalize=im/255
hflip=np.flip(im,0)
plt.imshow(normalize)
print(normalize)


[[[0.95686275 0.70588235 0.60784314]
  [0.94901961 0.69803922 0.6       ]
  [0.93333333 0.69411765 0.59215686]
  ...
  [0.95686275 0.78823529 0.75294118]
  [0.95686275 0.78823529 0.75294118]
  [0.95294118 0.78431373 0.74901961]]

 [[0.95686275 0.70588235 0.60784314]
  [0.95294118 0.70196078 0.60392157]
  [0.9372549  0.69803922 0.59607843]
  ...
  [0.95294118 0.78431373 0.74901961]
  [0.95294118 0.78431373 0.74901961]
  [0.95294118 0.78431373 0.74901961]]

 [[0.95294118 0.70196078 0.60392157]
  [0.95294118 0.70196078 0.60392157]
  [0.94509804 0.70588235 0.60392157]
  ...
  [0.95686275 0.78823529 0.75294118]
  [0.95686275 0.78823529 0.75294118]
  [0.95294118 0.78431373 0.74901961]]

 ...

 [[0.43921569 0.69411765 0.7254902 ]
  [0.43921569 0.69411765 0.7254902 ]
  [0.42352941 0.67843137 0.70980392]
  ...
  [0.26666667 0.21568627 0.        ]
  [0.26666667 0.21568627 0.        ]
  [0.26666667 0.21568627 0.        ]]

 [[0.43921569 0.69411765 0.7254902 ]
  [0.42745098 0.68235294 0.71372549]
